modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/RayzoRayy/RaysDongles/issues"
[[mods]]
modId="slurpiesdongles"
version="4.2.1"
displayName="Ray's Dongles"
updateJSONURL="https://raw.githubusercontent.com/RayzoRayy/RaysDongles/1.15.x/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/slurpies-dongles"
logoFile="logo.png"
credits="See https://github.com/RayzoRayy/RaysDongles/wiki/Contributors for credits"
authors="RayzoRayy"
description='''
Please see https://www.curseforge.com/minecraft/mc-mods/slurpies-dongles for more info on my mod, however, if you see this message, I hope that you have got my mod from Curse Forge! Any other site
does NOT have my permission to host my mod, and may contain malware or viruses. I support Curse Forge only.
'''

[[dependencies.slurpiesdongles]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1, 1.15.2]"
    ordering="NONE"
    side="BOTH"