
[Configs]

	#Config section for Actual Item tweaks
	[Configs."Actual Items"]
		#Enable or disable the Blender [ true / false default: true
		"Enable Blender" = true
		#Enable or disable the Knife [ true / false default: true
		"Enable Knife" = true
		#Enable or disable Nether Star chunks [ true / false default: true
		"Enable Nether Star chunks" = true
		#Enable or disable Pops Sign [true / false default: false
		"Enable Pops Sign" = false
		#Enable or disable the Stone Rod [true / false default: true
		"Enable Stone Rod" = true

	#Config section for Armor tweaks
	[Configs.Armor]
		#Setting this to false will disable Amethyst Armor [true / false default: true]
		"Enable Amethyst Armor" = true
		#Setting this to false will disable Ruby Armor [true / false default: true]
		"Enable Ruby Armor" = true
		#Setting this to false will disable Topaz Armor [true / false default: true]
		"Enable Topaz Armor" = true
		#Setting this to false will disable Withered Armor [true / false default: true]
		"Enable Withered Armor" = true

	#Config section for Block tweaks
	[Configs.Blocks]
		#Setting this to false will disable the placeable Blender [true / false default:true
		"Enable placeable Blender" = true
		#Setting this to false will disable the Reinforced Obsidian Block [true / false default:true
		"Enable Reinforced Obsidian Block" = true
		#Setting this to false will disable the Wild Crops [true / false default:true
		"Enable Wild Crops" = true
		#Setting this to false will disable the Deepslate Enderdust Ore [true / false default:true
		"Enable Deepslate Enderdust Ore" = true
		#Setting this to false will disable the Deepslate Ruby Ore [true / false default:true
		"Enable Deepslate Ruby Ore" = true
		#Setting this to false will disable the Deepslate Topaz Ore [true / false default:true
		"Enable Deepslate Topaz Ore" = true
		#Setting this to false will disable the Enderdust Ore [true / false default:true
		"Enable Enderdust Ore" = true
		#Setting this to false will disable the Ruby Ore [true / false default:true
		"Enable Ruby Ore" = true
		#Setting this to false will disable the Topaz Ore [true / false default:true
		"Enable Topaz Ore" = true

	#Config section for Charm tweaks
	[Configs.Charms]
		#Setting this to false will disable the Absorption Charm [true / false default: true]
		"Enable Absorption Charm" = true
		#Setting this to false will disable the Absorption Charm Tier 2 [true / false default: true]
		"Enable Absorption Charm Tier 2" = true
		#Setting this to false will disable the Fire Resistance Charm [true / false default: true]
		"Enable Fire Resistance Charm" = true
		#Setting this to false will disable the Night Vision Charm [true / false default: true]
		"Enable Night Vision Charm" = true
		#Setting this to false will disable the Regeneration Charm [true / false default: true]
		"Enable Regeneration Charm" = true
		#Setting this to false will disable the Regeneration Charm Tier 2 [true / false default: true]
		"Enable Regeneration Charm Tier 2" = true
		#Setting this to false will disable the Speed Charm [true / false default: true]
		"Enable Speed Charm" = true
		#Setting this to false will disable the Speed Charm Tier 2 [true / false default: true]
		"Enable Speed Charm Tier 2" = true
		#Setting this to false will disable the Strength Charm [true / false default: true]
		"Enable Strength Charm" = true
		#Setting this to false will disable the Strength Charm Tier 2 [true / false default: true]
		"Enable Strength Charm Tier 2" = true
		#Setting this to false will disable the Waterbreathing Charm [true / false default: true]
		"Enable Waterbreathing Charm" = true

	#Config section for Drink tweaks
	[Configs.Drinks]
		#Enable or disable the Apple Juice [true / false default: true
		"Enable Apple Juice" = true
		#Enable or disable the Apple Slushie [true / false default: true
		"Enable Apple Slushie" = true
		#Enable or disable the Carrot Juice [true / false default: true
		"Enable Carrot Juice" = true
		#Enable or disable the Lemonade [true / false default: true
		"Enable Lemonade" = true
		#Enable or disable the Melon Juice [true / false default: true
		"Enable Melon Juice" = true
		#Enable or disable the Melon Slushie [true / false default: true
		"Enable Melon Slushie" = true
		#Enable or disable the Orange Juice [true / false default: true
		"Enable Orange Juice" = true
		#Enable or disable the Orange Lemonade [true / false default: true
		"Enable Orange Lemonade" = true
		#Enable or disable the Orange Slushie [true / false default: true
		"Enable Orange Slushie" = true
		#Enable or disable the Strawberry Juice [true / false default: true
		"Enable Strawberry Juice" = true
		#Enable or disable the Strawberry Lemonade [true / false default: true
		"Enable Strawberry Lemonade" = true
		#Enable or disable the Strawberry Slushie [true / false default: true
		"Enable Strawberry Slushie" = true
		#Enable or disable the Tomato Juice [true / false default: true
		"Enable Tomato Juice" = true

	#Config section for Food Tweaks
	[Configs.Food]
		#Enable or Disable Apple Slice [true / false default: true
		"Enable Apple Slice" = true
		#Enable or Disable Bacon [true / false default: true
		"Enable Bacon" = true
		#Enable or Disable Bacon Egg Sandwich [true / false default: true
		"Enable Bacon Egg Sandwich" = true
		#Enable or Disable Bacon Potato Beef Stew [true / false default: true
		"Enable Bacon Potato Beef Stew" = true
		#Enable or Disable Bacon Potato Chicken Stew [true / false default: true
		"Enable Bacon Potato Chicken Stew" = true
		#Enable or Disable Beef Jerky [true / false default: true
		"Enable Beef Jerky" = true
		#Enable or Disable Beef Chicken Sandwich [true / false default: true
		"Enable Beef Chicken Sandwich" = true
		#Enable or Disable Beef Pork Sandwich [true / false default: true
		"Enable Beef Pork Sandwich" = true
		#Enable or Disable Beef Sandwich [true / false default: true
		"Enable Beef Sandwich" = true
		#Enable or Disable Cooked Carrot [true / false default: true
		"Enable Cooked Carrot" = true
		#Enable or Disable Carrot Stick [true / false default: true
		"Enable Carrot Stick" = true
		#Enable or Disable Chicken Nugget [true / false default: true
		"Enable Chicken Nugget" = true
		#Enable or Disable Chicken Sandwich [true / false default: true
		"Enable Chicken Sandwich" = true
		#Enable or Disable Chicken Pork Sandwich [true / false default: true
		"Enable Chicken Pork Sandwich" = true
		#Enable or Disable Cooked Carrot Stick [true / false default: true
		"Enable Cooked Carrot Stick" = true
		#Enable or Disable Cooked Rabbit Leg [true / false default: true
		"Enable Cooked Rabbit Leg" = true
		#Enable or Disable Corn [true / false default: true
		"Enable Corn" = true
		#Enable or Disable Eggs [true / false default: true
		"Enable Eggs" = true
		#Enable or Disable Golden Bacon [true / false default: true
		"Enable Golden Bacon" = true
		#Enable or Disable Golden Baked Potato [true / false default: true
		"Enable Golden Baked Potato" = true
		#Enable or Disable Golden Melon Slice [true / false default: true
		"Enable Golden Melon Slice" = true
		#Enable or Disable Golden Potato [true / false default: true
		"Enable Golden Potato" = true
		#Enable or Disable Melon Slice [true / false default: true
		"Enable Melon Slice" = true
		#Enable or Disable Mixed Fruit Bowl [true / false default: true
		"Enable Mixed Fruit Bowl" = true
		#Enable or Disable Mixed Seeds [true / false default: true
		"Enable Mixed Seeds" = true
		#Enable or Disable Pizza [true / false default: true
		"Enable Pizza" = true
		#Enable or Disable Pork Sandwich [true / false default: true
		"Enable Pork Sandwich" = true
		#Enable or Disable Potato Wedge [true / false default: true
		"Enable Potato Wedge" = true
		#Enable or Disable Rabbit Leg [true / false default: true
		"Enable Rabbit Leg" = true
		#Enable or Disable Raw Bacon [true / false default: true
		"Enable Raw Bacon" = true
		#Enable or Disable Raw Beef Slice [true / false default: true
		"Enable Raw Beef Slice" = true
		#Enable or Disable Raw Corn [true / false default: true
		"Enable Raw Corn" = true
		#Enable or Disable Raw Potato Wedge [true / false default: true
		"Enable Raw Potato Wedge" = true
		#Enable or Disable Roasted Apple [true / false default: true
		"Enable Roasted Apple" = true
		#Enable or Disable Roasted Beetroot Seeds [true / false default: true
		"Enable Roasted Beetroot Seeds" = true
		#Enable or Disable Roasted Melon Seeds [true / false default: true
		"Enable Roasted Melon Seeds" = true
		#Enable or Disable Roasted Mushroom [true / false default: true
		"Enable Roasted Mushroom" = true
		#Enable or Disable Roasted Pumpkin Seeds [true / false default: true
		"Enable Roasted Pumpkin Seeds" = true
		#Enable or Disable Roasted Red Mushroom [true / false default: true
		"Enable Roasted Red Mushroom" = true
		#Enable or Disable Roasted Seeds [true / false default: true
		"Enable Roasted Seeds" = true
		#Enable or Disable Strawberry [true / false default: true
		"Enable Strawberry" = true
		#Enable or Disable Sugar Coated Apple [true / false default: true
		"Enable Sugar Coated Apple" = true
		#Enable or Disable Sugar Coated Lemon [true / false default: true
		"Enable Sugar Coated Lemon" = true
		#Enable or Disable Sugar Coated Melon [true / false default: true
		"Enable Sugar Coated Melon" = true
		#Enable or Disable Sugar Coated Orange [true / false default: true
		"Enable Sugar Coated Orange" = true
		#Enable or Disable Sugar Coated Strawberry [true / false default: true
		"Enable Sugar Coated Strawberry" = true
		#Enable or Disable Toast [true / false default: true
		"Enable Toast" = true
		#Enable or Disable Toasted Bacon Egg Sandwich [true / false default: true
		"Enable Toasted Bacon Egg Sandwich" = true

	#Config section for Defensive Food Tweaks
	[Configs."Defensive Food"]
		#Enable or disable the Diamond Apple [true / false default: true
		"Enable Diamond Apple" = true
		#Enable or disable the Enchanted Diamond Apple [true / false default: true
		"Enable Enchanted Diamond Apple" = true
		#Enable or disable the Emerald Apple [true / false default: true
		"Enable Emerald Apple" = true
		#Enable or disable the Enchanted Emerald Apple [true / false default: true
		"Enable Enchanted Emerald Apple" = true
		#Enable or disable the Iron Apple [true / false default: true
		"Enable Iron Apple" = true
		#Enable or disable the Enchanted Iron Apple [true / false default: true
		"Enable Enchanted Iron Apple" = true
		#Enable or disable Holy Bread [true / false default: true
		"Enable Holy Bread" = true

	#Config section for mob drops tweaks
	[Configs."Mob Drops"]
		#Amount of Raw Bacon that Pigs drop : Default is 1 Raw Bacon drop, max is 5
		#Set the value to 0 to disable Raw Bacon drops
		#Range: 0 ~ 5
		"Raw Bacon drop amount" = 1

	#Config section for Amethyst tool tweaks
	[Configs.Amethyst]
		#Setting this to false will disable the entire Amethyst tool set [true / false default: true
		"Enable Amethyst tools" = true
		#Defines the BASE attack damage for Amethyst tools / modifying this will change damage for ALL Amethyst tools
		#Range: 0.0 ~ 40.0
		AttackDamage = 3.0
		#Defines the efficiency for Amethyst tools / DOES NOT AFFECT Axes, Battleaxes, Lumberaxes, OR Swords
		#Range: 0.0 ~ 40.0
		Efficiency = 8.0
		#Defines the enchantability for Amethyst tools [Default is 13)
		#Range: > 0
		Enchantability = 13
		#Defines the harvest level for Amethyst tools [Default is 3, min is 0, max is 10
		#Range: 0 ~ 10
		HarvestLevel = 3
		#Defines the max uses for Amethyst paxel [Default is 5217 uses, Axe + Pickaxe + Shovel durability = 5217
		#Range: > 0
		MaxUses = 5217

	#Config section for Ruby tool tweaks
	[Configs.Ruby]
		#Setting this to false will disable the entire Ruby tool set [true / false default: true
		"Enable Ruby tools" = true
		#Defines the BASE attack damage for Ruby tools / modifying this will change damage for ALL Ruby tools
		#Range: 0.0 ~ 40.0
		AttackDamage = 2.0
		#Defines the efficiency for Ruby tools / DOES NOT AFFECT Axes, Battleaxes, Lumberaxes, OR Swords
		#Range: 0.0 ~ 40.0
		Efficiency = 6.0
		#Defines the enchantability for Ruby tools [Default is 15)
		#Range: > 0
		Enchantability = 15
		#Defines the harvest level for Ruby tools [Default is 2, min is 0, max is 10
		#Range: 0 ~ 10
		HarvestLevel = 2
		#Defines the max uses for Ruby paxel [Default is 2163 uses, Axe + Pickaxe + Shovel durability = 2163
		#Range: > 0
		MaxUses = 2163

	#Config section for Topaz tool tweaks
	[Configs.Topaz]
		#Setting this to false will disable the entire Topaz tool set [true / false default: true
		"Enable Topaz tools" = true
		#Defines the BASE attack damage for Topaz tools / modifying this will change damage for ALL Topaz tools
		#Range: 0.0 ~ 40.0
		AttackDamage = 3.0
		#Defines the efficiency for Topaz tools / DOES NOT AFFECT Axes, Battleaxes, Lumberaxes, OR Swords
		#Range: 0.0 ~ 40.0
		Efficiency = 8.0
		#Defines the enchantability for Topaz tools [Default is 12)
		#Range: > 0
		Enchantability = 12
		#Defines the harvest level for Topaz tools [Default is 3, min is 0, max is 10
		#Range: 0 ~ 10
		HarvestLevel = 3
		#Defines the max uses for Topaz paxel [Default is 5679 uses, Axe + Pickaxe + Shovel durability = 5679
		#Range: > 0
		MaxUses = 5679

	#Config section for Mass Mining tool tweaks
	[Configs."Mass Mining"]
		#Setting this to false will disable the entire Mass Mining tool set [true / false default: true
		"Enable VM tools" = true
		#Defines the BASE attack damage for Mass Mining tools / modifying this will change damage for ALL Mass Mining tools
		#Range: 0.0 ~ 40.0
		AttackDamage = 1.0
		#Defines the efficiency for Mass Mining tools / DOES NOT AFFECT Axes, Battleaxes, Lumberaxes, OR Swords
		#Range: 0.0 ~ 40.0
		Efficiency = 4.0
		#Defines the enchantability for Mass Mining tools [Default is 5)
		#Range: > 0
		Enchantability = 5
		#Defines the harvest level for Mass Mining tools [Default is 1, min is 0, max is 10
		#Range: 0 ~ 10
		HarvestLevel = 1
		#Defines the max uses for Mass Mining tools [Default is 18200 uses
		#Range: > 0
		MaxUses = 18200

	#Config section for Withered tool tweaks
	[Configs.Withered]
		#Setting this to false will disable the entire Withered tool set [true / false default: true
		"Enable Withered tools" = true
		#Defines the BASE attack damage for Withered tools / modifying this will change damage for ALL Withered tools
		#Range: 0.0 ~ 40.0
		AttackDamage = 4.0
		#Defines the efficiency for Withered tools / DOES NOT AFFECT Axes, Battleaxes, Lumberaxes, OR Swords
		#Range: 0.0 ~ 40.0
		Efficiency = 11.0
		#Defines the enchantability for Withered tools [Default is 20)
		#Range: > 0
		Enchantability = 20
		#Defines the harvest level for Withered tools [Default is 4, min is 0, max is 10
		#Range: 0 ~ 10
		HarvestLevel = 4
		#Defines the max uses for Withered paxel [Default is 0 uses, / This is what makes it un-breakable
		#Range: > 0
		MaxUses = 0

	#Config section for extra Vanilla tool set tweaks
	[Configs."Extra Vanilla Tools"]
		#Setting this to false will disable the extra Diamond tools [true / false default: true
		"Enable extra Diamond tools" = true
		#Setting this to false will disable the extra Emerald tools [true / false default: true
		"Enable extra Emerald tools" = true
		#Setting this to false will disable the extra Gold tools [true / false default: true
		"Enable extra Gold tools" = true
		#Setting this to false will disable the extra Iron tools [true / false default: true
		"Enable extra Iron tools" = true
		#Setting this to false will disable the extra Netherite tools [true / false default: true
		"Enable extra Netherite tools" = true
		#Setting this to false will disable the extra Stone tools [true / false default: true
		"Enable extra Stone tools" = true
		#Setting this to false will disable the extra Wooden tools [true / false default: true
		"Enable extra Wooden tools" = true

